version: '3.3'
services:
  valheim-dedicated:
    working_dir: /home/steam/
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./valheim-data:/home/steam/valheim/"
      - "./valheim-scripts:/home/steam/valheim-scripts/"
      - "./Valheim:/home/steam/.config/unity3d/IronGate/Valheim/"
